const tenants = {
  essentials: [
    "7 ELEVEN",
    "METRO SUPERMARKET",
    "LAWSON 150NB",
    "99 RANCH",
    "WATSON 81MALL",
    "QUICKLEAN",
    "LAWSON 81MALL",
    "ASSI FRESH",
    "RELX",
    "WATSONS PTV1",
    "LAWSON BELMONT",
    "H20 LIFESOURCE INC.",
    "HAPPY PAW",
    "NATIONAL BOOKSTORE",
  ],
  food: [
    "ZABANA BAR",
    "POOLSIDE BAR",
    "SAVOY HOTEL",
    "BELMONT HOTEL",
    "TEALIVE",
    "TOKYO TOKYO",
    "MCDONALDS",
    "GILIGANS",
    "BOULANGERIE",
    "POPEYES",
    "S&R PIZZA",
    "SAMGYUPSALAMAT",
    "ROADSIDE BBQ",
    "VANKY HOTPOT",
    "GONGCHA",
    "STARBUCKS 81MALL",
    "LIL ORBITS'S MINI DONUT",
    "KFC",
    "PAN DE MANILA",
    "SERENITEA",
    "GERRY'S GRILL",
    "STARBUCKS BELMONT",
    "CHATIME",
    "SUBWAY",
    "THE ORANGE BUCKET",
  ],
  services: [
    "SOULSPACE",
    "DAVID SALON",
    "YATAI SPA",
    "DERMACARE",
    "AYUMI",
    "NUMI WELLNESS",
    "NAILS.GLOW",
    "MICH & MYLS",
    "NUAT THAI",
    "STRANDS SALON",
    "ANYTIME FITNESS",
    "YOUR DENTAL PLACE",
    "RICHMOMND DENTAL CLINIC",
    "SENOR BARBERSHOP",
    "YUNDING KTV",
    "AVIA INTERNATIONAL CLUB",
  ],
  prizes: [
    "Claim Essentials",
    "Claim Food",
    "Claim Services",
    "Claim Grand Prize",
  ],
};

module.exports = { tenants };
